### PR TITLE
Change default config filename

### PR DESCRIPTION
**Pull request by davwheat**
I've renamed the default `config.php` to `config.default.php`. This allows us to easily configure our development setups without risking an accidental push of our config.

## Summary

- `config.php` is now ignored in the `.gitignore`, preventing any accidental pushes.
- the default config is now `config.default.php`
- info about copying the default config is now in the README
- if someone forgets to copy the default config, we warn them (see below)

image

More info takes the user to the README on GitHub

### CODE REVIEW

**Comment by theaquarium** [comment]
Yeah, this looks pretty good to me. If you're changing some stuff in README, would you mind changing the Updating section to reflect that the automatic updater now is fully automatic and doesn't require downloading anything.

**Review by theaquarium — APPROVED** [review]
Looks great! Thank you so much. This will be our first release pushed with the automatic updater, so let's see how it goes!

**Comment by davwheat** [comment]
@theaquarium Done!

Do we still need `default_naming_scheme`, `use_default_naming_scheme_for_sharex`, and `use_default_naming_scheme_for_gallery`?

The default config doesn't have these in them, but I still get warned about not having them on the gallery page.

The config inside `mege_config.php` has these, but then doesn't have `sharex_upload_naming_scheme`, `text_upload_default_naming_scheme`, etc.

Which ones do we keep, and which do we remove?

image

**Comment by theaquarium** [comment]
Great catch, I'm not sure how that happened. The default naming scheme things are from the old config method and I must have somehow forgotten to remove them from the merge config. This is a bit beyond the scope of this PR, so I'll open up a new one to fix it.

**Pull request merged**
