### PR TITLE
Added PHP closing

### PR DESCRIPTION
**Pull request by Mosrod**
See: https://github.com/JoeGandy/ShareX-Custom-Upload/issues/7

### CODE REVIEW

**Comment by Natfan** [comment]
Doesn't necessarily add anything, but follows good syntax. Merging.

**Comment by DJkikisa** [comment]
> Doesn't necessarily add anything, but follows good syntax. Merging.

Since when it's good syntax, because what I have always had learned in this situation it's not and can make problems sometimes.

**Comment by DJkikisa** [comment]
> Doesn't necessarily add anything, but follows good syntax. Merging.

Hmm , then popular PHP frameworks use bad syntax. And many Developers says no to end tag @ this situation :)

**Comment by Natfan** [comment]
Really good point @DJkikisa, my bad! Thanks for teaching me something new 😛

**Comment by Natfan** [comment]
Merging #35 to revert this change.

**Pull request merged**
