### PR TITLE
Firefox loading fix

### PR DESCRIPTION
**Pull request by LordByronRS**
This will fix the infinite firefox loading bug on all accessible sites(index, login and register).

### CODE REVIEW

**Comment by LordByronRS** [comment]
#128

**Review by theaquarium — DISMISSED** [review]
LGTM

**Comment by LordByronRS** [comment]
Forgot the text viewer in my last commit.

**Review by theaquarium — APPROVED** [review]
Only just noticed these changes, sorry about that! Looks great!

**Review by JoeGandy — APPROVED** [review]

**Pull request merged**
