### PR TITLE
Add caching with ETag validation

### LINKED ISSUE #100: Upload caching
I think it'd be very beneficial to enable caching with an ETag.

https://github.com/JoeGandy/ShareX-Custom-Upload/blob/6571ae901bb1c006a0bc082ec7792d3835302b66/src/rewrite.php#L60-L62

Adding these lines below between L60 and L62 perform wonderfully. Can't do a PR right now, sorry!

This way, if a file changed, the updated file would be served as the ETag (SHA256 hash of the file)

```php
header('Cache-Control: public, max-age=360, stale-while-revalidate=120');

$etag = "test";
$etag_algo_used = "";

$time_start = microtime(true); 

if (PHP_INT_SIZE === 8) {
    # 64-bit, so we use SHA512 for faster performance
    $etag = hash_file("sha512", $file_path);
    $etag_algo_used = "SHA-512";
} else {
    # 32-bit (or other?), so we use SHA256 for faster performance
    $etag = hash_file("sha256", $file_path);
    $etag_algo_used = "SHA-256";
}

$time_end = microtime(true);

header('ETag: "'.$etag.'"');

# get time difference in ms
$time_diff = round(($time_end - $time_start) * 1000, 4);
header('X-ETag-Generation-Milliseconds: '.$time_diff);
header('X-ETag-Algorithm: '.$etag_algo_used);
```

### PR DESCRIPTION
**Pull request by theaquarium**
Resolves #100 

This implements caching for images and includes validation using image hashes and the ETag header.

Thanks to @davwheat for the code.

### CODE REVIEW

**Comment by JoeGandy** [comment]
Whats the reason for someone not wanting image caching?
just figuring out if adding a optional config is useful or not :)

**Comment by davwheat** [comment]
@JoeGandy Honestly, I can't think of one. The ETag handles if they change the file, or delete it.

I guess it's just better have to more configuration than less. Having an option won't hurt, but it should be on by default.

**Comment by theaquarium** [comment]
The only thing I thought could be a problem is if someone renames an image and then uploads something with a new name before their cache's TTL expires. The cache's TTL is currently set to 15 minutes, so the ETag won't do anything until 15 minutes after accessing the file, which could cause problems in certain situations. I think it's useful to just have a bunch of configuration options people can use if they need to.

**Comment by theaquarium** [comment]
I'll just leave the option since I think it's always good to have configuration.

**Pull request merged**
